### ISSUE TITLE
Wrong API version for Deployment kind

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/smart-gateway-operator#49]
https://github.com/infrawatch/smart-gateway-operator/blob/7ac81f607ad6fd145d9c49758c5c351af7d5bf42/roles/smartgateway/templates/deployment.yaml.j2#L1

I believe our apiVersion needs to be `apps/v1`. Currently doesn't deploy a SG properly on vanilla k8s.

**Comment by pleimer** [comment]
That's the same place the error occurred in OCP v4.4

**Comment by leifmadsen** [comment]
@pleimer awesome thanks! ok so I think we can change the apiVersion here, test on 4.3, and if it works there without issue, we can just make this the new default.
